apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  port: 8080
  accessPolicy:
    outbound:
      rules:
        - application: k9-mellomlagring
        - application: k9-joark
      external:
      {{#each externalHosts as |host|}}
          - host: {{host }}
      {{/each}}
  kafka:
    pool: {{kafka-pool}}
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 40m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  envFrom:
    - secret: {{app}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
